### ISSUE TITLE
`ActiveRecord::Base.serialize` no longer uses YAML by default.

### ISSUE THREAD

**Issue by RomainMorlevat** [tilo/embedded_localization#10]
Because of the following change in Rails 7.1:
>  `ActiveRecord::Base.serialize` no longer uses YAML by default.

https://github.com/rails/rails/blob/6b93fff8af32ef5e91f4ec3cfffb081d0553faf0/activerecord/CHANGELOG.md?plain=1#L995C5-L996C1

This Gem breaks ActiveAdmin routes in my case.

It's due to the following line:
https://github.com/tilo/embedded_localization/blob/bf0cf6eb571d3e985a580bce6dd7fcb2a69174e1/lib/embedded_localization/active_record/act_macro.rb#L26

It can be fixed with:
```diff
- serialize :i18n   # we should also protect it from direct assignment by the user
+ serialize :i18n, coder: YAML, type: Hash   # we should also protect it from direct assignment by the user
```

A better fix would be to use a `jsonb` column instead of a `text` one.

**Comment by tilo** [comment]
Hey @RomainMorlevat,
thank you for pointing this out!

version 1.3.0 will have this fix
